export const LOG_IN_USER = 'LOG_IN_USER'
export const LOG_IN_USER_STARTED = 'LOG_IN_USER_STARTED'
export const LOG_IN_USER_SUCCESS = 'LOG_IN_USER_SUCCESS'
export const LOG_IN_USER_FAILED = 'LOG_IN_USER_FAILED'

export const FETCH_EMPLOYERS_STARTED = 'FETCH_EMPLOYERS_STARTED'
export const FETCH_EMPLOYERS_SUCCESS = 'FETCH_EMPLOYERS_SUCCESS'
export const FETCH_EMPLOYERS_FAILED = 'FETCH_EMPLOYERS_FAILED'
